### ISSUE TITLE
Crash: Class not found when unmarshalling: com.nestlabs.sdk.Structure

### ISSUE THREAD

**Issue by unexpected62** [nestlabs/android-sdk-sample#1]
I implemented an activity similar to the sample and I experienced a crash in my app. I did some debugging and figured out how to reproduce it 100% even with this sample app.

1. Open the app (be already authenticated with a Nest account from a previous run)
2. Press the home button
3. `adb shell am kill com.nestlabs.sdk.sample`
4. Open the app again
5. Observe crash

These steps are simulating what happens if a user opens up the app, and presses the "home" button, sending the app to the background. If Android needs to reclaim system resources, it will kill the app. `adb shell am kill com.nestlabs.sdk.sample` simulates how Android would kill an app due to resource constraints. See the explanation in the [adb documentation here](http://developer.android.com/tools/help/shell.html),

> Kill all processes associated with <PACKAGE> (the app's package name). This command kills only processes that are safe to kill and that will not impact the user experience.

Note that this is different than force-stopping an app, as that does not simulate how Android kills an app due to resource constraints.

Here is the stack trace when the error occurs:

`04-16 11:38:33.757 7526-7526/? E/Parcel: Class not found when unmarshalling: com.nestlabs.sdk.Structure$Where
                                         java.lang.ClassNotFoundException: com.nestlabs.sdk.Structure$Where
                                             at java.lang.Class.classForName(Native Method)
                                             at java.lang.Class.forName(Class.java:324)
                                             at android.os.Parcel.readParcelableCreator(Parcel.java:2404)
                                             at android.os.Parcel.readParcelable(Parcel.java:2358)
                                             at android.os.Parcel.readValue(Parcel.java:2264)
                                             at android.os.Parcel.readMapInternal(Parcel.java:2597)
                                             at android.os.Parcel.readMap(Parcel.java:1725)
                                             at com.nestlabs.sdk.Structure.<init>(Structure.java:114)
                                             at com.nestlabs.sdk.Structure$1.createFromParcel(Structure.java:282)
                                             at com.nestlabs.sdk.Structure$1.createFromParcel(Structure.java:279)
                                             at android.os.Parcel.readParcelable(Parcel.java:2367)
                                             at android.os.Parcel.readValue(Parcel.java:2264)
                                             at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
                                             at android.os.BaseBundle.unparcel(BaseBundle.java:221)
                                             at android.os.BaseBundle.getBoolean(BaseBundle.java:659)
                                             at android.app.Activity.restoreHasCurrentPermissionRequest(Activity.java:6444)
                                             at android.app.Activity.performCreate(Activity.java:6250)
                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                             at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                             at android.os.Looper.loop(Looper.java:148)
                                             at android.app.ActivityThread.main(ActivityThread.java:5417)
                                             at java.lang.reflect.Method.invoke(Native Method)
                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                          Caused by: java.lang.ClassNotFoundException: com.nestlabs.sdk.Structure$Where
                                             at java.lang.Class.classForName(Native Method)
                                             at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                             at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                             at java.lang.Class.classForName(Native Method) 
                                             at java.lang.Class.forName(Class.java:324) 
                                             at android.os.Parcel.readParcelableCreator(Parcel.java:2404) 
                                             at android.os.Parcel.readParcelable(Parcel.java:2358) 
                                             at android.os.Parcel.readValue(Parcel.java:2264) 
                                             at android.os.Parcel.readMapInternal(Parcel.java:2597) 
                                             at android.os.Parcel.readMap(Parcel.java:1725) 
                                             at com.nestlabs.sdk.Structure.<init>(Structure.java:114) 
                                             at com.nestlabs.sdk.Structure$1.createFromParcel(Structure.java:282) 
                                             at com.nestlabs.sdk.Structure$1.createFromParcel(Structure.java:279) 
                                             at android.os.Parcel.readParcelable(Parcel.java:2367) 
                                             at android.os.Parcel.readValue(Parcel.java:2264) 
                                             at android.os.Parcel.readArrayMapInternal(Parcel.java:2614) 
                                             at android.os.BaseBundle.unparcel(BaseBundle.java:221) 
                                             at android.os.BaseBundle.getBoolean(BaseBundle.java:659) 
                                             at android.app.Activity.restoreHasCurrentPermissionRequest(Activity.java:6444) 
                                             at android.app.Activity.performCreate(Activity.java:6250) 
                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                             at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                             at android.os.Looper.loop(Looper.java:148) 
                                             at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                             at java.lang.reflect.Method.invoke(Native Method) 
                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                          Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
04-16 11:38:33.759 7526-7526/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.nestlabs.sdk.sample, PID: 7526
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nestlabs.sdk.sample/com.nestlabs.sdk.sample.MainActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.nestlabs.sdk.Structure$Where
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                  Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.nestlabs.sdk.Structure$Where
                                                     at android.os.Parcel.readParcelableCreator(Parcel.java:2432)
                                                     at android.os.Parcel.readParcelable(Parcel.java:2358)
                                                     at android.os.Parcel.readValue(Parcel.java:2264)
                                                     at android.os.Parcel.readMapInternal(Parcel.java:2597)
                                                     at android.os.Parcel.readMap(Parcel.java:1725)
                                                     at com.nestlabs.sdk.Structure.<init>(Structure.java:114)
                                                     at com.nestlabs.sdk.Structure$1.createFromParcel(Structure.java:282)
                                                     at com.nestlabs.sdk.Structure$1.createFromParcel(Structure.java:279)
                                                     at android.os.Parcel.readParcelable(Parcel.java:2367)
                                                     at android.os.Parcel.readValue(Parcel.java:2264)
                                                     at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
                                                     at android.os.BaseBundle.unparcel(BaseBundle.java:221)
                                                     at android.os.BaseBundle.getBoolean(BaseBundle.java:659)
                                                     at android.app.Activity.restoreHasCurrentPermissionRequest(Activity.java:6444)
                                                     at android.app.Activity.performCreate(Activity.java:6250)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) `

**Comment by unexpected62** [comment]
@ryanseys I think this is a problem with the parcelable implementation of the `Structure` class. What do you think?

**Comment by ryanseys** [comment]
Hmm interesting bug. It seems it's having issues unmarshalling Structure.Where 

I have tests in https://github.com/nestlabs/android-sdk/blob/master/sdk/src/test/java/com/nestlabs/sdk/StructureTest.java for that class, maybe we can find a case where this test doesn't pass properly (or the test improperly assumes something critical). Seems like a strange case to only have issues when you restart the app... maybe that has something to do with it too?

**Comment by ryanseys** [comment]
Can you try with the latest version (1.1.0) of the android-sdk dependency and let me know if the problem continues? Thanks.

**Comment by unexpected62** [comment]
Yes, I will give it a shot. I saw that issue in the other thread and wondered if it would make a difference as well.

**Comment by unexpected62** [comment]
@ryanseys Crash still happens using 1.1.0. Same stack trace.

**Comment by unexpected62** [comment]
@ryanseys I have a work-around that might help you debug the problem.

If in `MainActivity.java` I remove the following from `onCreate()`:

```java
    if (savedInstanceState != null) {
        mThermostat = savedInstanceState.getParcelable(THERMOSTAT_KEY);
        mStructure = savedInstanceState.getParcelable(STRUCTURE_KEY);
        updateViews();
    }
```

And if I also just delete the overridden `OnSaveInstanceState()`:

```java
    @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        outState.putParcelable(THERMOSTAT_KEY, mThermostat);
        outState.putParcelable(STRUCTURE_KEY, mStructure);
    }
```

then I am unable to reproduce the crash. Of course, now we don't take advantage of retrieving these objects from disk when restarting the app, but I'll take the hit for now to avoid the crash.
